<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\CreateReq\StreamOptions instead.
     * @deprecated
     */
    class CreateReq_StreamOptions {}
}
class_exists(CreateReq\StreamOptions::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\CreateReq_StreamOptions is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\CreateReq\StreamOptions instead', E_USER_DEPRECATED);

