<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\CreateReq\Settings instead.
     * @deprecated
     */
    class CreateReq_Settings {}
}
class_exists(CreateReq\Settings::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\CreateReq_Settings is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\CreateReq\Settings instead', E_USER_DEPRECATED);

