<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions\Expression instead.
     * @deprecated
     */
    class CreateReq_AllOptions_FilterOptions_Expression {}
}
class_exists(CreateReq\AllOptions\FilterOptions\Expression::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\CreateReq_AllOptions_FilterOptions_Expression is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions\Expression instead', E_USER_DEPRECATED);

