<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions instead.
     * @deprecated
     */
    class CreateReq_AllOptions_FilterOptions {}
}
class_exists(CreateReq\AllOptions\FilterOptions::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\CreateReq_AllOptions_FilterOptions is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions instead', E_USER_DEPRECATED);

