<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\CreateReq\Position instead.
     * @deprecated
     */
    class CreateReq_Position {}
}
class_exists(CreateReq\Position::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\CreateReq_Position is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\CreateReq\Position instead', E_USER_DEPRECATED);

