<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.GetInfoResp</code>
 */
class GetInfoResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.SubscriptionInfo subscription_info = 1;</code>
     */
    protected $subscription_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Persistent_subscriptions\SubscriptionInfo $subscription_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.SubscriptionInfo subscription_info = 1;</code>
     * @return \Event_store\Client\Persistent_subscriptions\SubscriptionInfo|null
     */
    public function getSubscriptionInfo()
    {
        return $this->subscription_info;
    }

    public function hasSubscriptionInfo()
    {
        return isset($this->subscription_info);
    }

    public function clearSubscriptionInfo()
    {
        unset($this->subscription_info);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.SubscriptionInfo subscription_info = 1;</code>
     * @param \Event_store\Client\Persistent_subscriptions\SubscriptionInfo $var
     * @return $this
     */
    public function setSubscriptionInfo($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\SubscriptionInfo::class);
        $this->subscription_info = $var;

        return $this;
    }

}

