<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ListReq\StreamOption instead.
     * @deprecated
     */
    class ListReq_StreamOption {}
}
class_exists(ListReq\StreamOption::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ListReq_StreamOption is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ListReq\StreamOption instead', E_USER_DEPRECATED);

