<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ListReq\Options instead.
     * @deprecated
     */
    class ListReq_Options {}
}
class_exists(ListReq\Options::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ListReq_Options is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ListReq\Options instead', E_USER_DEPRECATED);

