<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent instead.
     * @deprecated
     */
    class ReadResp_ReadEvent {}
}
class_exists(ReadResp\ReadEvent::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ReadResp_ReadEvent is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent instead', E_USER_DEPRECATED);

