<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ReadReq\Nack instead.
     * @deprecated
     */
    class ReadReq_Nack {}
}
class_exists(ReadReq\Nack::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ReadReq_Nack is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ReadReq\Nack instead', E_USER_DEPRECATED);

