<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.ReadReq</code>
 */
class ReadReq extends \Google\Protobuf\Internal\Message
{
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Persistent_subscriptions\ReadReq\Options $options
     *     @type \Event_store\Client\Persistent_subscriptions\ReadReq\Ack $ack
     *     @type \Event_store\Client\Persistent_subscriptions\ReadReq\Nack $nack
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Options options = 1;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ReadReq\Options|null
     */
    public function getOptions()
    {
        return $this->readOneof(1);
    }

    public function hasOptions()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Options options = 1;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ReadReq\Options $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ReadReq\Options::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Ack ack = 2;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ReadReq\Ack|null
     */
    public function getAck()
    {
        return $this->readOneof(2);
    }

    public function hasAck()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Ack ack = 2;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ReadReq\Ack $var
     * @return $this
     */
    public function setAck($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ReadReq\Ack::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Nack nack = 3;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ReadReq\Nack|null
     */
    public function getNack()
    {
        return $this->readOneof(3);
    }

    public function hasNack()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Nack nack = 3;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ReadReq\Nack $var
     * @return $this
     */
    public function setNack($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ReadReq\Nack::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

