<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ReadReq\Ack instead.
     * @deprecated
     */
    class ReadReq_Ack {}
}
class_exists(ReadReq\Ack::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ReadReq_Ack is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ReadReq\Ack instead', E_USER_DEPRECATED);

