<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.ReadResp</code>
 */
class ReadResp extends \Google\Protobuf\Internal\Message
{
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent $event
     *     @type \Event_store\Client\Persistent_subscriptions\ReadResp\SubscriptionConfirmation $subscription_confirmation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadResp.ReadEvent event = 1;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent|null
     */
    public function getEvent()
    {
        return $this->readOneof(1);
    }

    public function hasEvent()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadResp.ReadEvent event = 1;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadResp.SubscriptionConfirmation subscription_confirmation = 2;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ReadResp\SubscriptionConfirmation|null
     */
    public function getSubscriptionConfirmation()
    {
        return $this->readOneof(2);
    }

    public function hasSubscriptionConfirmation()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadResp.SubscriptionConfirmation subscription_confirmation = 2;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ReadResp\SubscriptionConfirmation $var
     * @return $this
     */
    public function setSubscriptionConfirmation($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ReadResp\SubscriptionConfirmation::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

