<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ReadReq\Nack\Action instead.
     * @deprecated
     */
    class ReadReq_Nack_Action {}
}
class_exists(ReadReq\Nack\Action::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ReadReq_Nack_Action is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ReadReq\Nack\Action instead', E_USER_DEPRECATED);

