<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent\RecordedEvent instead.
     * @deprecated
     */
    class ReadResp_ReadEvent_RecordedEvent {}
}
class_exists(ReadResp\ReadEvent\RecordedEvent::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\ReadResp_ReadEvent_RecordedEvent is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\ReadResp\ReadEvent\RecordedEvent instead', E_USER_DEPRECATED);

