<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\SubscriptionInfo\Measurement instead.
     * @deprecated
     */
    class SubscriptionInfo_Measurement {}
}
class_exists(SubscriptionInfo\Measurement::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\SubscriptionInfo_Measurement is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\SubscriptionInfo\Measurement instead', E_USER_DEPRECATED);

