<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\SubscriptionInfo\ConnectionInfo instead.
     * @deprecated
     */
    class SubscriptionInfo_ConnectionInfo {}
}
class_exists(SubscriptionInfo\ConnectionInfo::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\SubscriptionInfo_ConnectionInfo is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\SubscriptionInfo\ConnectionInfo instead', E_USER_DEPRECATED);

