<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\UpdateReq\ConsumerStrategy instead.
     * @deprecated
     */
    class UpdateReq_ConsumerStrategy {}
}
class_exists(UpdateReq\ConsumerStrategy::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\UpdateReq_ConsumerStrategy is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\UpdateReq\ConsumerStrategy instead', E_USER_DEPRECATED);

