<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Persistent_subscriptions\UpdateReq\Options instead.
     * @deprecated
     */
    class UpdateReq_Options {}
}
class_exists(UpdateReq\Options::class);
@trigger_error('Event_store\Client\Persistent_subscriptions\UpdateReq_Options is deprecated and will be removed in the next major release. Use Event_store\Client\Persistent_subscriptions\UpdateReq\Options instead', E_USER_DEPRECATED);

