<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\ListReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.ListReq.Options</code>
 */
class Options extends \Google\Protobuf\Internal\Message
{
    protected $list_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\PBEmpty $list_all_subscriptions
     *     @type \Event_store\Client\Persistent_subscriptions\ListReq\StreamOption $list_for_stream
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty list_all_subscriptions = 1;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getListAllSubscriptions()
    {
        return $this->readOneof(1);
    }

    public function hasListAllSubscriptions()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty list_all_subscriptions = 1;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setListAllSubscriptions($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ListReq.StreamOption list_for_stream = 2;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ListReq\StreamOption|null
     */
    public function getListForStream()
    {
        return $this->readOneof(2);
    }

    public function hasListForStream()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ListReq.StreamOption list_for_stream = 2;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ListReq\StreamOption $var
     * @return $this
     */
    public function setListForStream($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ListReq\StreamOption::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getListOption()
    {
        return $this->whichOneof("list_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Options::class, \Event_store\Client\Persistent_subscriptions\ListReq_Options::class);

