<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams\AppendResp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.streams.AppendResp.Success</code>
 */
class Success extends \Google\Protobuf\Internal\Message
{
    protected $current_revision_option;
    protected $position_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $current_revision
     *     @type \Event_store\Client\PBEmpty $no_stream
     *     @type \Event_store\Client\Streams\AppendResp\Position $position
     *     @type \Event_store\Client\PBEmpty $no_position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Streams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 current_revision = 1;</code>
     * @return int|string
     */
    public function getCurrentRevision()
    {
        return $this->readOneof(1);
    }

    public function hasCurrentRevision()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>uint64 current_revision = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_stream = 2;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getNoStream()
    {
        return $this->readOneof(2);
    }

    public function hasNoStream()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_stream = 2;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setNoStream($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendResp.Position position = 3;</code>
     * @return \Event_store\Client\Streams\AppendResp\Position|null
     */
    public function getPosition()
    {
        return $this->readOneof(3);
    }

    public function hasPosition()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendResp.Position position = 3;</code>
     * @param \Event_store\Client\Streams\AppendResp\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Streams\AppendResp\Position::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_position = 4;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getNoPosition()
    {
        return $this->readOneof(4);
    }

    public function hasNoPosition()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_position = 4;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setNoPosition($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCurrentRevisionOption()
    {
        return $this->whichOneof("current_revision_option");
    }

    /**
     * @return string
     */
    public function getPositionOption()
    {
        return $this->whichOneof("position_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Success::class, \Event_store\Client\Streams\AppendResp_Success::class);

