<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams\ReadReq\Options;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.streams.ReadReq.Options.ControlOption</code>
 */
class ControlOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 compatibility = 1;</code>
     */
    protected $compatibility = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $compatibility
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Streams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 compatibility = 1;</code>
     * @return int
     */
    public function getCompatibility()
    {
        return $this->compatibility;
    }

    /**
     * Generated from protobuf field <code>uint32 compatibility = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCompatibility($var)
    {
        GPBUtil::checkUint32($var);
        $this->compatibility = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ControlOption::class, \Event_store\Client\Streams\ReadReq_Options_ControlOption::class);

