<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams\ReadReq\Options;

use UnexpectedValueException;

/**
 * Protobuf type <code>event_store.client.streams.ReadReq.Options.ReadDirection</code>
 */
class ReadDirection
{
    /**
     * Generated from protobuf enum <code>Forwards = 0;</code>
     */
    const Forwards = 0;
    /**
     * Generated from protobuf enum <code>Backwards = 1;</code>
     */
    const Backwards = 1;

    private static $valueToName = [
        self::Forwards => 'Forwards',
        self::Backwards => 'Backwards',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ReadDirection::class, \Event_store\Client\Streams\ReadReq_Options_ReadDirection::class);

