<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\UpdateReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.UpdateReq.Settings</code>
 */
class Settings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool resolve_links = 1;</code>
     */
    protected $resolve_links = false;
    /**
     * Generated from protobuf field <code>uint64 revision = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $revision = 0;
    /**
     * Generated from protobuf field <code>bool extra_statistics = 3;</code>
     */
    protected $extra_statistics = false;
    /**
     * Generated from protobuf field <code>int32 max_retry_count = 5;</code>
     */
    protected $max_retry_count = 0;
    /**
     * Generated from protobuf field <code>int32 min_checkpoint_count = 7;</code>
     */
    protected $min_checkpoint_count = 0;
    /**
     * Generated from protobuf field <code>int32 max_checkpoint_count = 8;</code>
     */
    protected $max_checkpoint_count = 0;
    /**
     * Generated from protobuf field <code>int32 max_subscriber_count = 9;</code>
     */
    protected $max_subscriber_count = 0;
    /**
     * Generated from protobuf field <code>int32 live_buffer_size = 10;</code>
     */
    protected $live_buffer_size = 0;
    /**
     * Generated from protobuf field <code>int32 read_batch_size = 11;</code>
     */
    protected $read_batch_size = 0;
    /**
     * Generated from protobuf field <code>int32 history_buffer_size = 12;</code>
     */
    protected $history_buffer_size = 0;
    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.UpdateReq.ConsumerStrategy named_consumer_strategy = 13;</code>
     */
    protected $named_consumer_strategy = 0;
    protected $message_timeout;
    protected $checkpoint_after;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $resolve_links
     *     @type int|string $revision
     *     @type bool $extra_statistics
     *     @type int $max_retry_count
     *     @type int $min_checkpoint_count
     *     @type int $max_checkpoint_count
     *     @type int $max_subscriber_count
     *     @type int $live_buffer_size
     *     @type int $read_batch_size
     *     @type int $history_buffer_size
     *     @type int $named_consumer_strategy
     *     @type int|string $message_timeout_ticks
     *     @type int $message_timeout_ms
     *     @type int|string $checkpoint_after_ticks
     *     @type int $checkpoint_after_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool resolve_links = 1;</code>
     * @return bool
     */
    public function getResolveLinks()
    {
        return $this->resolve_links;
    }

    /**
     * Generated from protobuf field <code>bool resolve_links = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setResolveLinks($var)
    {
        GPBUtil::checkBool($var);
        $this->resolve_links = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 2 [deprecated = true];</code>
     * @return int|string
     * @deprecated
     */
    public function getRevision()
    {
        @trigger_error('revision is deprecated.', E_USER_DEPRECATED);
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 2 [deprecated = true];</code>
     * @param int|string $var
     * @return $this
     * @deprecated
     */
    public function setRevision($var)
    {
        @trigger_error('revision is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool extra_statistics = 3;</code>
     * @return bool
     */
    public function getExtraStatistics()
    {
        return $this->extra_statistics;
    }

    /**
     * Generated from protobuf field <code>bool extra_statistics = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setExtraStatistics($var)
    {
        GPBUtil::checkBool($var);
        $this->extra_statistics = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_retry_count = 5;</code>
     * @return int
     */
    public function getMaxRetryCount()
    {
        return $this->max_retry_count;
    }

    /**
     * Generated from protobuf field <code>int32 max_retry_count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRetryCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_retry_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 min_checkpoint_count = 7;</code>
     * @return int
     */
    public function getMinCheckpointCount()
    {
        return $this->min_checkpoint_count;
    }

    /**
     * Generated from protobuf field <code>int32 min_checkpoint_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMinCheckpointCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_checkpoint_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_checkpoint_count = 8;</code>
     * @return int
     */
    public function getMaxCheckpointCount()
    {
        return $this->max_checkpoint_count;
    }

    /**
     * Generated from protobuf field <code>int32 max_checkpoint_count = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxCheckpointCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_checkpoint_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_subscriber_count = 9;</code>
     * @return int
     */
    public function getMaxSubscriberCount()
    {
        return $this->max_subscriber_count;
    }

    /**
     * Generated from protobuf field <code>int32 max_subscriber_count = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxSubscriberCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_subscriber_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 live_buffer_size = 10;</code>
     * @return int
     */
    public function getLiveBufferSize()
    {
        return $this->live_buffer_size;
    }

    /**
     * Generated from protobuf field <code>int32 live_buffer_size = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLiveBufferSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->live_buffer_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 read_batch_size = 11;</code>
     * @return int
     */
    public function getReadBatchSize()
    {
        return $this->read_batch_size;
    }

    /**
     * Generated from protobuf field <code>int32 read_batch_size = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setReadBatchSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->read_batch_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 history_buffer_size = 12;</code>
     * @return int
     */
    public function getHistoryBufferSize()
    {
        return $this->history_buffer_size;
    }

    /**
     * Generated from protobuf field <code>int32 history_buffer_size = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setHistoryBufferSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->history_buffer_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.UpdateReq.ConsumerStrategy named_consumer_strategy = 13;</code>
     * @return int
     */
    public function getNamedConsumerStrategy()
    {
        return $this->named_consumer_strategy;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.UpdateReq.ConsumerStrategy named_consumer_strategy = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setNamedConsumerStrategy($var)
    {
        GPBUtil::checkEnum($var, \Event_store\Client\Persistent_subscriptions\UpdateReq\ConsumerStrategy::class);
        $this->named_consumer_strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 message_timeout_ticks = 4;</code>
     * @return int|string
     */
    public function getMessageTimeoutTicks()
    {
        return $this->readOneof(4);
    }

    public function hasMessageTimeoutTicks()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>int64 message_timeout_ticks = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageTimeoutTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 message_timeout_ms = 14;</code>
     * @return int
     */
    public function getMessageTimeoutMs()
    {
        return $this->readOneof(14);
    }

    public function hasMessageTimeoutMs()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>int32 message_timeout_ms = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageTimeoutMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 checkpoint_after_ticks = 6;</code>
     * @return int|string
     */
    public function getCheckpointAfterTicks()
    {
        return $this->readOneof(6);
    }

    public function hasCheckpointAfterTicks()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>int64 checkpoint_after_ticks = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCheckpointAfterTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 checkpoint_after_ms = 15;</code>
     * @return int
     */
    public function getCheckpointAfterMs()
    {
        return $this->readOneof(15);
    }

    public function hasCheckpointAfterMs()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>int32 checkpoint_after_ms = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setCheckpointAfterMs($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessageTimeout()
    {
        return $this->whichOneof("message_timeout");
    }

    /**
     * @return string
     */
    public function getCheckpointAfter()
    {
        return $this->whichOneof("checkpoint_after");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Settings::class, \Event_store\Client\Persistent_subscriptions\UpdateReq_Settings::class);

