<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\ReadReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.ReadReq.Options</code>
 */
class Options extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string group_name = 2;</code>
     */
    protected $group_name = '';
    /**
     * Generated from protobuf field <code>int32 buffer_size = 3;</code>
     */
    protected $buffer_size = 0;
    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Options.UUIDOption uuid_option = 4;</code>
     */
    protected $uuid_option = null;
    protected $stream_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\StreamIdentifier $stream_identifier
     *     @type \Event_store\Client\PBEmpty $all
     *     @type string $group_name
     *     @type int $buffer_size
     *     @type \Event_store\Client\Persistent_subscriptions\ReadReq\Options\UUIDOption $uuid_option
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     * @return \Event_store\Client\StreamIdentifier|null
     */
    public function getStreamIdentifier()
    {
        return $this->readOneof(1);
    }

    public function hasStreamIdentifier()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     * @param \Event_store\Client\StreamIdentifier $var
     * @return $this
     */
    public function setStreamIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\StreamIdentifier::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty all = 5;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getAll()
    {
        return $this->readOneof(5);
    }

    public function hasAll()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty all = 5;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 buffer_size = 3;</code>
     * @return int
     */
    public function getBufferSize()
    {
        return $this->buffer_size;
    }

    /**
     * Generated from protobuf field <code>int32 buffer_size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBufferSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->buffer_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Options.UUIDOption uuid_option = 4;</code>
     * @return \Event_store\Client\Persistent_subscriptions\ReadReq\Options\UUIDOption|null
     */
    public function getUuidOption()
    {
        return $this->uuid_option;
    }

    public function hasUuidOption()
    {
        return isset($this->uuid_option);
    }

    public function clearUuidOption()
    {
        unset($this->uuid_option);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.ReadReq.Options.UUIDOption uuid_option = 4;</code>
     * @param \Event_store\Client\Persistent_subscriptions\ReadReq\Options\UUIDOption $var
     * @return $this
     */
    public function setUuidOption($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\ReadReq\Options\UUIDOption::class);
        $this->uuid_option = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getStreamOption()
    {
        return $this->whichOneof("stream_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Options::class, \Event_store\Client\Persistent_subscriptions\ReadReq_Options::class);

