<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto

namespace GPBMetadata;

class Status
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Code::initOnce();
        $pool->internalAddGeneratedFile(
            '
ó
status.proto
google.rpc
code.proto"`
Status
code (2.google.rpc.Code
message (	%
details (2.google.protobuf.AnyBa
com.google.rpcBStatusProtoPZ7google.golang.org/genproto/googleapis/rpc/status;statusø¢RPCbproto3'
        , true);

        static::$is_initialized = true;
    }
}

