<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

namespace Event_store\Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.MaximumAppendEventSizeExceeded</code>
 */
class MaximumAppendEventSizeExceeded extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     */
    protected $eventId = '';
    /**
     * Generated from protobuf field <code>uint32 proposedEventSize = 2;</code>
     */
    protected $proposedEventSize = 0;
    /**
     * Generated from protobuf field <code>uint32 maxAppendEventSize = 3;</code>
     */
    protected $maxAppendEventSize = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $eventId
     *     @type int $proposedEventSize
     *     @type int $maxAppendEventSize
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shared::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     * @return string
     */
    public function getEventId()
    {
        return $this->eventId;
    }

    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 proposedEventSize = 2;</code>
     * @return int
     */
    public function getProposedEventSize()
    {
        return $this->proposedEventSize;
    }

    /**
     * Generated from protobuf field <code>uint32 proposedEventSize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProposedEventSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->proposedEventSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 maxAppendEventSize = 3;</code>
     * @return int
     */
    public function getMaxAppendEventSize()
    {
        return $this->maxAppendEventSize;
    }

    /**
     * Generated from protobuf field <code>uint32 maxAppendEventSize = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxAppendEventSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->maxAppendEventSize = $var;

        return $this;
    }

}

