<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

namespace Event_store\Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.StreamIdentifier</code>
 */
class StreamIdentifier extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes stream_name = 3;</code>
     */
    protected $stream_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shared::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes stream_name = 3;</code>
     * @return string
     */
    public function getStreamName()
    {
        return $this->stream_name;
    }

    /**
     * Generated from protobuf field <code>bytes stream_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStreamName($var)
    {
        GPBUtil::checkString($var, False);
        $this->stream_name = $var;

        return $this;
    }

}

