<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

namespace Event_store\Client;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\UUID\Structured instead.
     * @deprecated
     */
    class UUID_Structured {}
}
class_exists(UUID\Structured::class);
@trigger_error('Event_store\Client\UUID_Structured is deprecated and will be removed in the next major release. Use Event_store\Client\UUID\Structured instead', E_USER_DEPRECATED);

