<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

namespace Event_store\Client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.WrongExpectedVersion</code>
 */
class WrongExpectedVersion extends \Google\Protobuf\Internal\Message
{
    protected $current_stream_revision_option;
    protected $expected_stream_position_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $current_stream_revision
     *     @type \Google\Protobuf\GPBEmpty $current_no_stream
     *     @type int|string $expected_stream_position
     *     @type \Google\Protobuf\GPBEmpty $expected_any
     *     @type \Google\Protobuf\GPBEmpty $expected_stream_exists
     *     @type \Google\Protobuf\GPBEmpty $expected_no_stream
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shared::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 current_stream_revision = 1;</code>
     * @return int|string
     */
    public function getCurrentStreamRevision()
    {
        return $this->readOneof(1);
    }

    public function hasCurrentStreamRevision()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>uint64 current_stream_revision = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentStreamRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty current_no_stream = 2;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getCurrentNoStream()
    {
        return $this->readOneof(2);
    }

    public function hasCurrentNoStream()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty current_no_stream = 2;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setCurrentNoStream($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expected_stream_position = 3;</code>
     * @return int|string
     */
    public function getExpectedStreamPosition()
    {
        return $this->readOneof(3);
    }

    public function hasExpectedStreamPosition()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>uint64 expected_stream_position = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpectedStreamPosition($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty expected_any = 4;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getExpectedAny()
    {
        return $this->readOneof(4);
    }

    public function hasExpectedAny()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty expected_any = 4;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setExpectedAny($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty expected_stream_exists = 5;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getExpectedStreamExists()
    {
        return $this->readOneof(5);
    }

    public function hasExpectedStreamExists()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty expected_stream_exists = 5;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setExpectedStreamExists($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty expected_no_stream = 6;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getExpectedNoStream()
    {
        return $this->readOneof(6);
    }

    public function hasExpectedNoStream()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty expected_no_stream = 6;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setExpectedNoStream($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCurrentStreamRevisionOption()
    {
        return $this->whichOneof("current_stream_revision_option");
    }

    /**
     * @return string
     */
    public function getExpectedStreamPositionOption()
    {
        return $this->whichOneof("expected_stream_position_option");
    }

}

