<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.streams.AppendResp</code>
 */
class AppendResp extends \Google\Protobuf\Internal\Message
{
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Streams\AppendResp\Success $success
     *     @type \Event_store\Client\Streams\AppendResp\WrongExpectedVersion $wrong_expected_version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Streams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendResp.Success success = 1;</code>
     * @return \Event_store\Client\Streams\AppendResp\Success|null
     */
    public function getSuccess()
    {
        return $this->readOneof(1);
    }

    public function hasSuccess()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendResp.Success success = 1;</code>
     * @param \Event_store\Client\Streams\AppendResp\Success $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Streams\AppendResp\Success::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendResp.WrongExpectedVersion wrong_expected_version = 2;</code>
     * @return \Event_store\Client\Streams\AppendResp\WrongExpectedVersion|null
     */
    public function getWrongExpectedVersion()
    {
        return $this->readOneof(2);
    }

    public function hasWrongExpectedVersion()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendResp.WrongExpectedVersion wrong_expected_version = 2;</code>
     * @param \Event_store\Client\Streams\AppendResp\WrongExpectedVersion $var
     * @return $this
     */
    public function setWrongExpectedVersion($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Streams\AppendResp\WrongExpectedVersion::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

