<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\AppendReq\Options instead.
     * @deprecated
     */
    class AppendReq_Options {}
}
class_exists(AppendReq\Options::class);
@trigger_error('Event_store\Client\Streams\AppendReq_Options is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\AppendReq\Options instead', E_USER_DEPRECATED);

