<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\AppendReq\ProposedMessage instead.
     * @deprecated
     */
    class AppendReq_ProposedMessage {}
}
class_exists(AppendReq\ProposedMessage::class);
@trigger_error('Event_store\Client\Streams\AppendReq_ProposedMessage is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\AppendReq\ProposedMessage instead', E_USER_DEPRECATED);

