<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\AppendResp\WrongExpectedVersion instead.
     * @deprecated
     */
    class AppendResp_WrongExpectedVersion {}
}
class_exists(AppendResp\WrongExpectedVersion::class);
@trigger_error('Event_store\Client\Streams\AppendResp_WrongExpectedVersion is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\AppendResp\WrongExpectedVersion instead', E_USER_DEPRECATED);

