<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.streams.AppendReq</code>
 */
class AppendReq extends \Google\Protobuf\Internal\Message
{
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Streams\AppendReq\Options $options
     *     @type \Event_store\Client\Streams\AppendReq\ProposedMessage $proposed_message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Streams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendReq.Options options = 1;</code>
     * @return \Event_store\Client\Streams\AppendReq\Options|null
     */
    public function getOptions()
    {
        return $this->readOneof(1);
    }

    public function hasOptions()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendReq.Options options = 1;</code>
     * @param \Event_store\Client\Streams\AppendReq\Options $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Streams\AppendReq\Options::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendReq.ProposedMessage proposed_message = 2;</code>
     * @return \Event_store\Client\Streams\AppendReq\ProposedMessage|null
     */
    public function getProposedMessage()
    {
        return $this->readOneof(2);
    }

    public function hasProposedMessage()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.AppendReq.ProposedMessage proposed_message = 2;</code>
     * @param \Event_store\Client\Streams\AppendReq\ProposedMessage $var
     * @return $this
     */
    public function setProposedMessage($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Streams\AppendReq\ProposedMessage::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

