<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\AppendResp\Success instead.
     * @deprecated
     */
    class AppendResp_Success {}
}
class_exists(AppendResp\Success::class);
@trigger_error('Event_store\Client\Streams\AppendResp_Success is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\AppendResp\Success instead', E_USER_DEPRECATED);

