<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\AppendResp\Position instead.
     * @deprecated
     */
    class AppendResp_Position {}
}
class_exists(AppendResp\Position::class);
@trigger_error('Event_store\Client\Streams\AppendResp_Position is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\AppendResp\Position instead', E_USER_DEPRECATED);

