<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.streams.DeleteResp</code>
 */
class DeleteResp extends \Google\Protobuf\Internal\Message
{
    protected $position_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Streams\DeleteResp\Position $position
     *     @type \Event_store\Client\PBEmpty $no_position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Streams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.DeleteResp.Position position = 1;</code>
     * @return \Event_store\Client\Streams\DeleteResp\Position|null
     */
    public function getPosition()
    {
        return $this->readOneof(1);
    }

    public function hasPosition()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.streams.DeleteResp.Position position = 1;</code>
     * @param \Event_store\Client\Streams\DeleteResp\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Streams\DeleteResp\Position::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_position = 2;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getNoPosition()
    {
        return $this->readOneof(2);
    }

    public function hasNoPosition()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_position = 2;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setNoPosition($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPositionOption()
    {
        return $this->whichOneof("position_option");
    }

}

