<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadResp\ReadEvent instead.
     * @deprecated
     */
    class ReadResp_ReadEvent {}
}
class_exists(ReadResp\ReadEvent::class);
@trigger_error('Event_store\Client\Streams\ReadResp_ReadEvent is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadResp\ReadEvent instead', E_USER_DEPRECATED);

