<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadResp\SubscriptionConfirmation instead.
     * @deprecated
     */
    class ReadResp_SubscriptionConfirmation {}
}
class_exists(ReadResp\SubscriptionConfirmation::class);
@trigger_error('Event_store\Client\Streams\ReadResp_SubscriptionConfirmation is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadResp\SubscriptionConfirmation instead', E_USER_DEPRECATED);

