<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadReq\Options\FilterOptions\Expression instead.
     * @deprecated
     */
    class ReadReq_Options_FilterOptions_Expression {}
}
class_exists(ReadReq\Options\FilterOptions\Expression::class);
@trigger_error('Event_store\Client\Streams\ReadReq_Options_FilterOptions_Expression is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadReq\Options\FilterOptions\Expression instead', E_USER_DEPRECATED);

