<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadResp\Checkpoint instead.
     * @deprecated
     */
    class ReadResp_Checkpoint {}
}
class_exists(ReadResp\Checkpoint::class);
@trigger_error('Event_store\Client\Streams\ReadResp_Checkpoint is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadResp\Checkpoint instead', E_USER_DEPRECATED);

