<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadResp\FellBehind instead.
     * @deprecated
     */
    class ReadResp_FellBehind {}
}
class_exists(ReadResp\FellBehind::class);
@trigger_error('Event_store\Client\Streams\ReadResp_FellBehind is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadResp\FellBehind instead', E_USER_DEPRECATED);

