<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadResp\CaughtUp instead.
     * @deprecated
     */
    class ReadResp_CaughtUp {}
}
class_exists(ReadResp\CaughtUp::class);
@trigger_error('Event_store\Client\Streams\ReadResp_CaughtUp is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadResp\CaughtUp instead', E_USER_DEPRECATED);

