<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadResp\StreamNotFound instead.
     * @deprecated
     */
    class ReadResp_StreamNotFound {}
}
class_exists(ReadResp\StreamNotFound::class);
@trigger_error('Event_store\Client\Streams\ReadResp_StreamNotFound is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadResp\StreamNotFound instead', E_USER_DEPRECATED);

