<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams;

if (false) {
    /**
     * This class is deprecated. Use Event_store\Client\Streams\ReadReq\Options\UUIDOption instead.
     * @deprecated
     */
    class ReadReq_Options_UUIDOption {}
}
class_exists(ReadReq\Options\UUIDOption::class);
@trigger_error('Event_store\Client\Streams\ReadReq_Options_UUIDOption is deprecated and will be removed in the next major release. Use Event_store\Client\Streams\ReadReq\Options\UUIDOption instead', E_USER_DEPRECATED);

