<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions.Expression</code>
 */
class Expression extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string regex = 1;</code>
     */
    protected $regex = '';
    /**
     * Generated from protobuf field <code>repeated string prefix = 2;</code>
     */
    private $prefix;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $regex
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $prefix
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string regex = 1;</code>
     * @return string
     */
    public function getRegex()
    {
        return $this->regex;
    }

    /**
     * Generated from protobuf field <code>string regex = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegex($var)
    {
        GPBUtil::checkString($var, True);
        $this->regex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string prefix = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Generated from protobuf field <code>repeated string prefix = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefix($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->prefix = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Expression::class, \Event_store\Client\Persistent_subscriptions\CreateReq_AllOptions_FilterOptions_Expression::class);

