<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\CreateReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.CreateReq.AllOptions</code>
 */
class AllOptions extends \Google\Protobuf\Internal\Message
{
    protected $all_option;
    protected $filter_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Persistent_subscriptions\CreateReq\Position $position
     *     @type \Event_store\Client\PBEmpty $start
     *     @type \Event_store\Client\PBEmpty $end
     *     @type \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions $filter
     *     @type \Event_store\Client\PBEmpty $no_filter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.Position position = 1;</code>
     * @return \Event_store\Client\Persistent_subscriptions\CreateReq\Position|null
     */
    public function getPosition()
    {
        return $this->readOneof(1);
    }

    public function hasPosition()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.Position position = 1;</code>
     * @param \Event_store\Client\Persistent_subscriptions\CreateReq\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\CreateReq\Position::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty start = 2;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getStart()
    {
        return $this->readOneof(2);
    }

    public function hasStart()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty start = 2;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty end = 3;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getEnd()
    {
        return $this->readOneof(3);
    }

    public function hasEnd()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty end = 3;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions filter = 4;</code>
     * @return \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions|null
     */
    public function getFilter()
    {
        return $this->readOneof(4);
    }

    public function hasFilter()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.AllOptions.FilterOptions filter = 4;</code>
     * @param \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions\FilterOptions::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_filter = 5;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getNoFilter()
    {
        return $this->readOneof(5);
    }

    public function hasNoFilter()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty no_filter = 5;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setNoFilter($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAllOption()
    {
        return $this->whichOneof("all_option");
    }

    /**
     * @return string
     */
    public function getFilterOption()
    {
        return $this->whichOneof("filter_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AllOptions::class, \Event_store\Client\Persistent_subscriptions\CreateReq_AllOptions::class);

