<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\CreateReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.CreateReq.Options</code>
 */
class Options extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $stream_identifier = null;
    /**
     * Generated from protobuf field <code>string group_name = 2;</code>
     */
    protected $group_name = '';
    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.Settings settings = 3;</code>
     */
    protected $settings = null;
    protected $stream_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\Persistent_subscriptions\CreateReq\StreamOptions $stream
     *     @type \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions $all
     *     @type \Event_store\Client\StreamIdentifier $stream_identifier
     *     @type string $group_name
     *     @type \Event_store\Client\Persistent_subscriptions\CreateReq\Settings $settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.StreamOptions stream = 4;</code>
     * @return \Event_store\Client\Persistent_subscriptions\CreateReq\StreamOptions|null
     */
    public function getStream()
    {
        return $this->readOneof(4);
    }

    public function hasStream()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.StreamOptions stream = 4;</code>
     * @param \Event_store\Client\Persistent_subscriptions\CreateReq\StreamOptions $var
     * @return $this
     */
    public function setStream($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\CreateReq\StreamOptions::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.AllOptions all = 5;</code>
     * @return \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions|null
     */
    public function getAll()
    {
        return $this->readOneof(5);
    }

    public function hasAll()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.AllOptions all = 5;</code>
     * @param \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\CreateReq\AllOptions::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1 [deprecated = true];</code>
     * @return \Event_store\Client\StreamIdentifier|null
     * @deprecated
     */
    public function getStreamIdentifier()
    {
        @trigger_error('stream_identifier is deprecated.', E_USER_DEPRECATED);
        return $this->stream_identifier;
    }

    public function hasStreamIdentifier()
    {
        @trigger_error('stream_identifier is deprecated.', E_USER_DEPRECATED);
        return isset($this->stream_identifier);
    }

    public function clearStreamIdentifier()
    {
        @trigger_error('stream_identifier is deprecated.', E_USER_DEPRECATED);
        unset($this->stream_identifier);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1 [deprecated = true];</code>
     * @param \Event_store\Client\StreamIdentifier $var
     * @return $this
     * @deprecated
     */
    public function setStreamIdentifier($var)
    {
        @trigger_error('stream_identifier is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \Event_store\Client\StreamIdentifier::class);
        $this->stream_identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.Settings settings = 3;</code>
     * @return \Event_store\Client\Persistent_subscriptions\CreateReq\Settings|null
     */
    public function getSettings()
    {
        return $this->settings;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.persistent_subscriptions.CreateReq.Settings settings = 3;</code>
     * @param \Event_store\Client\Persistent_subscriptions\CreateReq\Settings $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\Persistent_subscriptions\CreateReq\Settings::class);
        $this->settings = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getStreamOption()
    {
        return $this->whichOneof("stream_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Options::class, \Event_store\Client\Persistent_subscriptions\CreateReq_Options::class);

