<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\CreateReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.CreateReq.StreamOptions</code>
 */
class StreamOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     */
    protected $stream_identifier = null;
    protected $revision_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\StreamIdentifier $stream_identifier
     *     @type int|string $revision
     *     @type \Event_store\Client\PBEmpty $start
     *     @type \Event_store\Client\PBEmpty $end
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     * @return \Event_store\Client\StreamIdentifier|null
     */
    public function getStreamIdentifier()
    {
        return $this->stream_identifier;
    }

    public function hasStreamIdentifier()
    {
        return isset($this->stream_identifier);
    }

    public function clearStreamIdentifier()
    {
        unset($this->stream_identifier);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     * @param \Event_store\Client\StreamIdentifier $var
     * @return $this
     */
    public function setStreamIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\StreamIdentifier::class);
        $this->stream_identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 2;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->readOneof(2);
    }

    public function hasRevision()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty start = 3;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getStart()
    {
        return $this->readOneof(3);
    }

    public function hasStart()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty start = 3;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty end = 4;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getEnd()
    {
        return $this->readOneof(4);
    }

    public function hasEnd()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty end = 4;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRevisionOption()
    {
        return $this->whichOneof("revision_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StreamOptions::class, \Event_store\Client\Persistent_subscriptions\CreateReq_StreamOptions::class);

