<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent.proto

namespace Event_store\Client\Persistent_subscriptions\ReadReq\Options;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.persistent_subscriptions.ReadReq.Options.UUIDOption</code>
 */
class UUIDOption extends \Google\Protobuf\Internal\Message
{
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\PBEmpty $structured
     *     @type \Event_store\Client\PBEmpty $string
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Persistent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty structured = 1;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getStructured()
    {
        return $this->readOneof(1);
    }

    public function hasStructured()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty structured = 1;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setStructured($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty string = 2;</code>
     * @return \Event_store\Client\PBEmpty|null
     */
    public function getString()
    {
        return $this->readOneof(2);
    }

    public function hasString()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.Empty string = 2;</code>
     * @param \Event_store\Client\PBEmpty $var
     * @return $this
     */
    public function setString($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\PBEmpty::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UUIDOption::class, \Event_store\Client\Persistent_subscriptions\ReadReq_Options_UUIDOption::class);

