<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streams.proto

namespace Event_store\Client\Streams\BatchAppendReq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>event_store.client.streams.BatchAppendReq.Options</code>
 */
class Options extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     */
    protected $stream_identifier = null;
    protected $expected_stream_position;
    protected $deadline_option;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Event_store\Client\StreamIdentifier $stream_identifier
     *     @type int|string $stream_position
     *     @type \Google\Protobuf\GPBEmpty $no_stream
     *     @type \Google\Protobuf\GPBEmpty $any
     *     @type \Google\Protobuf\GPBEmpty $stream_exists
     *     @type \Google\Protobuf\Timestamp $deadline_21_10_0
     *     @type \Google\Protobuf\Duration $deadline
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Streams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     * @return \Event_store\Client\StreamIdentifier|null
     */
    public function getStreamIdentifier()
    {
        return $this->stream_identifier;
    }

    public function hasStreamIdentifier()
    {
        return isset($this->stream_identifier);
    }

    public function clearStreamIdentifier()
    {
        unset($this->stream_identifier);
    }

    /**
     * Generated from protobuf field <code>.event_store.client.StreamIdentifier stream_identifier = 1;</code>
     * @param \Event_store\Client\StreamIdentifier $var
     * @return $this
     */
    public function setStreamIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Event_store\Client\StreamIdentifier::class);
        $this->stream_identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 stream_position = 2;</code>
     * @return int|string
     */
    public function getStreamPosition()
    {
        return $this->readOneof(2);
    }

    public function hasStreamPosition()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>uint64 stream_position = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStreamPosition($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty no_stream = 3;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getNoStream()
    {
        return $this->readOneof(3);
    }

    public function hasNoStream()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty no_stream = 3;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setNoStream($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty any = 4;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getAny()
    {
        return $this->readOneof(4);
    }

    public function hasAny()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty any = 4;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setAny($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty stream_exists = 5;</code>
     * @return \Google\Protobuf\GPBEmpty|null
     */
    public function getStreamExists()
    {
        return $this->readOneof(5);
    }

    public function hasStreamExists()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Empty stream_exists = 5;</code>
     * @param \Google\Protobuf\GPBEmpty $var
     * @return $this
     */
    public function setStreamExists($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\GPBEmpty::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp deadline_21_10_0 = 6;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDeadline21100()
    {
        return $this->readOneof(6);
    }

    public function hasDeadline21100()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp deadline_21_10_0 = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDeadline21100($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration deadline = 7;</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getDeadline()
    {
        return $this->readOneof(7);
    }

    public function hasDeadline()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration deadline = 7;</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setDeadline($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getExpectedStreamPosition()
    {
        return $this->whichOneof("expected_stream_position");
    }

    /**
     * @return string
     */
    public function getDeadlineOption()
    {
        return $this->whichOneof("deadline_option");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Options::class, \Event_store\Client\Streams\BatchAppendReq_Options::class);

